### ISSUE TITLE
Some plotting functions do not work with current pyvista (0.42.1)

### ISSUE THREAD

**Issue by rfiorella** [lanl/tinerator#31]
Some functions for visualizing unstructured meshes error with current pyvista. Occurs in both the examples (e.g., Borden.ipynb) and in package tests.

Error is: "AttributeError: 'UnstructuredGrid' object has no attribute 'cell_arrays'".

(Possibly related to #23?)

**Comment by rfiorella** [comment]
Replacing `cell_arrays` with `cell_data` upgrades (downgrades?) this error to a segmentation fault, possibly related to how the last test exits (doesn't work well in CI or locally).

**Comment by rfiorella** [comment]
Several potential causes of seg fault and plotting window issues:
https://github.com/pyvista/pyvista/issues/3869
https://github.com/pyvista/pyvista/issues/1096
https://github.com/pyvista/pyvista/issues/1033

**Comment by rfiorella** [comment]
Example notebooks do seem to be working locally as of: 3b620e2269a6234ba9bc28c52475c15e1a8e5bfc
